export const sortTypes = [
  {
    label: 'Price (Highest)',
    value: 'price-desc',
  },
  {
    label: 'Price (Lowest)',
    value: 'price-asc',
  },
];

export const sampleProducts = [
  {
    id: 1,
    name: 'Kittens Rush',
    category: 'game',
    description: 'A simple turn based game with cute kittens',
    price: 20,
    image: 'https://placehold.co/200',
    rating: 5,
    stock: 10,
  },
  {
    id: 2,
    name: 'Cozy Cat Bed',
    category: 'pet supplies',
    description: 'A soft and comfortable bed for your feline friend',
    price: 30,
    image: 'https://placehold.co/200',
    rating: 4.8,
    stock: 15,
  },
  {
    id: 3,
    name: 'Catnip Plush Toy',
    category: 'toys',
    description: 'A plush toy filled with catnip for endless fun',
    price: 10,
    image: 'https://placehold.co/200',
    rating: 4.5,
    stock: 25,
  },
  {
    id: 4,
    name: 'Whisker Wonderland Puzzle',
    category: 'game',
    description: 'A challenging puzzle featuring adorable cat artwork',
    price: 18,
    image: 'https://placehold.co/200',
    rating: 4.7,
    stock: 12,
  },
  {
    id: 5,
    name: 'Cute Cat Mug',
    category: 'home & kitchen',
    description: 'A ceramic mug with a cute cat design',
    price: 15,
    image: 'https://placehold.co/200',
    rating: 4.6,
    stock: 20,
  },
  {
    id: 6,
    name: 'Cat-Themed Notebook',
    category: 'stationery',
    description: 'A notebook featuring adorable cat illustrations',
    price: 12,
    image: 'https://placehold.co/200',
    rating: 4.9,
    stock: 18,
  },
  {
    id: 7,
    name: 'Interactive Laser Toy',
    category: 'toys',
    description: 'A laser pointer toy to keep your cat entertained',
    price: 22,
    image: 'https://placehold.co/200',
    rating: 4.7,
    stock: 0,
  },
  {
    id: 8,
    name: 'Kitten Socks',
    category: 'clothing',
    description: 'Cozy socks with cute kitten prints',
    price: 8,
    image: 'https://placehold.co/200',
    rating: 4.5,
    stock: 40,
  },
  {
    id: 9,
    name: 'Cat Ear Headphones',
    category: 'electronics',
    description: 'Wireless headphones with stylish cat ears',
    price: 50,
    image: 'https://placehold.co/200',
    rating: 4.8,
    stock: 10,
  },
  {
    id: 10,
    name: 'Purring Companion Robot',
    category: 'gadgets',
    description: 'A robotic cat that purrs and moves like a real cat',
    price: 80,
    image: 'https://placehold.co/200',
    rating: 4.6,
    stock: 5,
  },
  {
    id: 11,
    name: 'Cat Shaped Pillow',
    category: 'home decor',
    description: 'A soft, cat-shaped pillow for extra comfort',
    price: 25,
    image: 'https://placehold.co/200',
    rating: 4.7,
    stock: 15,
  },
  {
    id: 12,
    name: 'Whiskers Wine Glass',
    category: 'home & kitchen',
    description: 'A wine glass featuring an etched cat design',
    price: 18,
    image: 'https://placehold.co/200',
    rating: 4.9,
    stock: 20,
  },
  {
    id: 13,
    name: 'Paw Print Blanket',
    category: 'home & living',
    description: 'A cozy blanket with a cute paw print design',
    price: 35,
    image: 'https://placehold.co/200',
    rating: 4.8,
    stock: 10,
  },
  {
    id: 14,
    name: 'Cat-Themed Phone Case',
    category: 'accessories',
    description: 'A stylish phone case with a cat illustration',
    price: 16,
    image: 'https://placehold.co/200',
    rating: 4.5,
    stock: 25,
  },
  {
    id: 15,
    name: 'Automatic Cat Feeder',
    category: 'pet supplies',
    description: 'An automatic feeder to keep your cat well-fed',
    price: 45,
    image: 'https://placehold.co/200',
    rating: 4.6,
    stock: 8,
  },
  {
    id: 16,
    name: 'Cat Ears Beanie',
    category: 'clothing',
    description: 'A warm beanie with adorable cat ears',
    price: 14,
    image: 'https://placehold.co/200',
    rating: 4.8,
    stock: 20,
  },
  {
    id: 17,
    name: 'Cat Calendar 2025',
    category: 'stationery',
    description: 'A wall calendar featuring cute cat photos',
    price: 10,
    image: 'https://placehold.co/200',
    rating: 4.9,
    stock: 30,
  },
  {
    id: 18,
    name: 'Cat-Themed Backpack',
    category: 'accessories',
    description: 'A stylish backpack with cat patterns',
    price: 38,
    image: 'https://placehold.co/200',
    rating: 4.7,
    stock: 12,
  },
  {
    id: 19,
    name: 'Meow Mix Puzzle Game',
    category: 'game',
    description: 'A fun puzzle game where you match different cats',
    price: 22,
    image: 'https://placehold.co/200',
    rating: 4.6,
    stock: 18,
  },
  {
    id: 20,
    name: 'Cat Paw Oven Mitts',
    category: 'home & kitchen',
    description: 'Oven mitts shaped like cute cat paws',
    price: 20,
    image: 'https://placehold.co/200',
    rating: 4.8,
    stock: 15,
  },
];
