export const sortTypes = [
  {
    label: 'Price (Highest)',
    value: 'price-desc',
  },
  {
    label: 'Price (Lowest)',
    value: 'price-asc',
  },
  {
    label: 'Name (A-Z)',
    value: 'name-asc',
  },
  {
    label: 'Name (Z-A)',
    value: 'name-desc',
  },
];

export const sampleProducts = [
  {
    id: 1,
    name: 'Kittens Rush',
    category: 'game',
    description: 'A simple turn based game with cute kittens',
    price: 20,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/GAME.jpg?updatedAt=1739289199771',
    rating: 5,
    stock: 10,
  },
  {
    id: 2,
    name: 'Cozy Cat Bed',
    category: 'pet supplies',
    description: 'A soft and comfortable bed for your feline friend',
    price: 30,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/PET_SUPLIES.jpg?updatedAt=1739289199961',
    rating: 4.8,
    stock: 15,
  },
  {
    id: 3,
    name: 'Catnip Plush Toy',
    category: 'toys',
    description: 'A plush toy filled with catnip for endless fun',
    price: 10,
    image: 'https://placehold.co/200',
    rating: 4.5,
    stock: 25,
  },
  {
    id: 4,
    name: 'Whisker Wonderland Puzzle',
    category: 'game',
    description: 'A challenging puzzle featuring adorable cat artwork',
    price: 18,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/GAME.jpg?updatedAt=1739289199771',
    rating: 4.7,
    stock: 12,
  },
  {
    id: 5,
    name: 'Cute Cat Mug',
    category: 'home & kitchen',
    description: 'A ceramic mug with a cute cat design',
    price: 15,
    image: 'https://placehold.co/200',
    rating: 4.6,
    stock: 20,
  },
  {
    id: 6,
    name: 'Cat-Themed Notebook',
    category: 'stationery',
    description: 'A notebook featuring adorable cat illustrations',
    price: 12,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/STATIONERY.jpg?updatedAt=1739289200128',
    rating: 4.9,
    stock: 18,
  },
  {
    id: 7,
    name: 'Interactive Laser Toy',
    category: 'toys',
    description: 'A laser pointer toy to keep your cat entertained',
    price: 22,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/TOYS.jpg?updatedAt=1739289200003',
    rating: 4.7,
    stock: 0,
  },
  {
    id: 8,
    name: 'Kitten Socks',
    category: 'clothing',
    description: 'Cozy socks with cute kitten prints',
    price: 8,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/CLOTHING.jpg?updatedAt=1739289199887',
    rating: 4.5,
    stock: 40,
  },
  {
    id: 9,
    name: 'Cat Ear Headphones',
    category: 'electronics',
    description: 'Wireless headphones with stylish cat ears',
    price: 50,
    image: 'https://placehold.co/200',
    rating: 4.8,
    stock: 10,
  },
  {
    id: 10,
    name: 'Purring Companion Robot',
    category: 'gadgets',
    description: 'A robotic cat that purrs and moves like a real cat',
    price: 80,
    image: 'https://placehold.co/200',
    rating: 4.6,
    stock: 5,
  },
  {
    id: 11,
    name: 'Cat Shaped Pillow',
    category: 'home decor',
    description: 'A soft, cat-shaped pillow for extra comfort',
    price: 25,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/HOME.jpg?updatedAt=1739289199872',
    rating: 4.7,
    stock: 15,
  },
  {
    id: 12,
    name: 'Whiskers Wine Glass',
    category: 'home & kitchen',
    description: 'A wine glass featuring an etched cat design',
    price: 18,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/OTHER.jpg?updatedAt=1739289199898',
    rating: 4.9,
    stock: 20,
  },
  {
    id: 13,
    name: 'Paw Print Blanket',
    category: 'home & living',
    description: 'A cozy blanket with a cute paw print design',
    price: 35,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/HOME.jpg?updatedAt=1739289199872',
    rating: 4.8,
    stock: 10,
  },
  {
    id: 14,
    name: 'Cat-Themed Phone Case',
    category: 'accessories',
    description: 'A stylish phone case with a cat illustration',
    price: 16,
    image: 'https://placehold.co/200',
    rating: 4.5,
    stock: 25,
  },
  {
    id: 15,
    name: 'Automatic Cat Feeder',
    category: 'pet supplies',
    description: 'An automatic feeder to keep your cat well-fed',
    price: 45,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/PET_SUPLIES.jpg?updatedAt=1739289199961',
    rating: 4.6,
    stock: 8,
  },
  {
    id: 16,
    name: 'Cat Ears Beanie',
    category: 'clothing',
    description: 'A warm beanie with adorable cat ears',
    price: 14,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/CLOTHING.jpg?updatedAt=1739289199887',
    rating: 4.8,
    stock: 20,
  },
  {
    id: 17,
    name: 'Cat Calendar 2025',
    category: 'stationery',
    description: 'A wall calendar featuring cute cat photos',
    price: 10,
    image: 'https://placehold.co/200',
    rating: 4.9,
    stock: 30,
  },
  {
    id: 18,
    name: 'Cat-Themed Backpack',
    category: 'accessories',
    description: 'A stylish backpack with cat patterns',
    price: 38,
    image: 'https://placehold.co/200',
    rating: 4.7,
    stock: 12,
  },
  {
    id: 19,
    name: 'Meow Mix Puzzle Game',
    category: 'game',
    description: 'A fun puzzle game where you match different cats',
    price: 22,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/GAME.jpg?updatedAt=1739289199771',
    rating: 4.6,
    stock: 18,
  },
  {
    id: 20,
    name: 'Cat Paw Oven Mitts',
    category: 'home & kitchen',
    description: 'Oven mitts shaped like cute cat paws',
    price: 20,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/HOME.jpg?updatedAt=1739289199872',
    rating: 4.8,
    stock: 15,
  },
];

const products = [
  // GAME
  {
    name: 'Cat Adventure Board Game',
    category: 'GAME',
    description: 'A fun and interactive board game where players guide their cats through various adventures.',
    price: 25,
    rating: 5,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/GAME.jpg?updatedAt=1739289199771',
    stock: 15,
  },
  {
    name: 'Virtual Cat Simulator',
    category: 'GAME',
    description: 'A digital game that lets you experience life from a cat’s perspective.',
    price: 15,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/15.jpg?updatedAt=1739952826462',
    rating: 4,
    stock: 30,
  },
  {
    name: 'Cat Puzzle Challenge',
    category: 'GAME',
    description: 'A puzzle game featuring adorable cat illustrations and different difficulty levels.',
    price: 13,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/23.jpg?updatedAt=1739953780448',
    rating: 4,
    stock: 25,
  },

  // BOOKS
  {
    name: 'The Cat Encyclopedia',
    category: 'BOOKS',
    description: 'A comprehensive guide to cat breeds, behavior, and care.',
    price: 30,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/12.jpg?updatedAt=1739952824887',
    rating: 5,
    stock: 10,
  },
  {
    name: 'Adventures of Whiskers',
    category: 'BOOKS',
    description: "A children's book following the journey of a curious cat.",
    price: 20,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/22.jpg?updatedAt=1739952819486',
    rating: 4,
    stock: 18,
  },
  {
    name: 'Training Your Cat',
    category: 'BOOKS',
    description: 'A practical guide to training your feline friend.',
    price: 18,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/6.jpg?updatedAt=1739952823001',
    rating: 4,
    stock: 22,
  },

  // PET_SUPPLIES
  {
    name: 'Cat Scratching Post',
    category: 'PET_SUPPLIES',
    description: 'A durable scratching post to keep your cat entertained and protect furniture.',
    price: 40,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/31.jpg?updatedAt=1739954370802',
    rating: 5,
    stock: 12,
  },
  {
    name: 'Self-Cleaning Litter Box',
    category: 'PET_SUPPLIES',
    description: 'An automatic litter box that keeps itself clean, making pet care easier.',
    price: 100,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/34.jpg?updatedAt=1739954508064',
    rating: 5,
    stock: 5,
  },
  {
    name: 'Interactive Cat Feeder',
    category: 'PET_SUPPLIES',
    description: 'A fun feeder that makes mealtime more engaging for your cat.',
    price: 25,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/2.jpg?updatedAt=1739952819576',
    rating: 4,
    stock: 20,
  },

  // TOYS
  {
    name: 'Feather Wand Toy',
    category: 'TOYS',
    description: 'An interactive toy with feathers that keeps cats entertained.',
    price: 10,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/TOYS.jpg?updatedAt=1739289200003',
    rating: 5,
    stock: 30,
  },
  {
    name: 'Catnip Plush Mouse',
    category: 'TOYS',
    description: 'A soft plush mouse infused with catnip for hours of fun.',
    price: 8,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/4.jpg?updatedAt=1739952822753',
    rating: 4,
    stock: 40,
  },
  {
    name: 'Rolling Ball Track',
    category: 'TOYS',
    description: "A multi-level ball track that stimulates your cat's hunting instincts.",
    price: 15,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/5.jpg?updatedAt=1739952822868',
    rating: 4,
    stock: 25,
  },

  // STATIONERY
  {
    name: 'Cat-Themed Notebook',
    category: 'STATIONERY',
    description: 'A stylish notebook with adorable cat illustrations.',
    price: 12,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/14.jpg?updatedAt=1739952825286',
    rating: 5,
    stock: 22,
  },
  {
    name: 'Cat Gel Pen Set',
    category: 'STATIONERY',
    description: 'A set of smooth-writing gel pens with cat designs.',
    price: 10,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/9.jpg?updatedAt=1739952822356',
    rating: 4,
    stock: 30,
  },
  {
    name: 'Cat Sticker Pack',
    category: 'STATIONERY',
    description: 'A pack of cute cat stickers for decorating notebooks and planners.',
    price: 7,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/26.jpg?updatedAt=1739953780301',
    rating: 4,
    stock: 35,
  },

  // CLOTHING
  {
    name: 'Cat Print T-Shirt',
    category: 'CLOTHING',
    description: 'A soft cotton t-shirt featuring an adorable cat print.',
    price: 20,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/10.jpg?updatedAt=17399528258728',
    rating: 5,
    stock: 18,
  },
  {
    name: 'Knit Cat Sweater',
    category: 'CLOTHING',
    description: 'A cozy sweater with embroidered cat designs.',
    price: 35,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/CLOTHING.jpg?updatedAt=1739289199887',
    rating: 5,
    stock: 10,
  },
  {
    name: 'Cat-Themed Socks',
    category: 'CLOTHING',
    description: 'A pack of warm and comfy socks with cute cat patterns.',
    price: 12,
    image: 'hhttps://ik.imagekit.io/h4sspbp2a/products/3.jpg?updatedAt=1739952823020',
    rating: 4,
    stock: 25,
  },

  // ELECTRONICS
  {
    name: 'Cat Ear Headphones',
    category: 'ELECTRONICS',
    description: 'Wireless headphones with cat ears that light up.',
    price: 50,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/21.jpg?updatedAt=1739952822701',
    rating: 5,
    stock: 8,
  },
  {
    name: 'Smart Pet Camera',
    category: 'ELECTRONICS',
    description: 'A pet camera with two-way audio to monitor your cat remotely.',
    price: 80,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/28.jpg?updatedAt=1739954370881',
    rating: 5,
    stock: 6,
  },
  {
    name: 'Automatic Laser Toy',
    category: 'ELECTRONICS',
    description: 'A laser toy that keeps your cat entertained with random movement patterns.',
    price: 30,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/ELECTRONICS.jpg?updatedAt=1739289199954',
    rating: 4,
    stock: 12,
  },

  // HOME
  {
    name: 'Cat-Shaped Pillow',
    category: 'HOME',
    description: 'A soft and cuddly pillow in the shape of a cat.',
    price: 25,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/18.jpg?updatedAt=1739952819260',
    rating: 5,
    stock: 15,
  },
  {
    name: 'Cat-Themed Coffee Mug',
    category: 'HOME',
    description: 'A ceramic coffee mug with a cute cat design.',
    price: 15,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/20.jpg?updatedAt=1739952819778',
    rating: 4,
    stock: 20,
  },
  {
    name: 'Cat Wall Clock',
    category: 'HOME',
    description: 'A stylish wall clock featuring a playful cat design.',
    price: 35,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/HOME.jpg?updatedAt=1739289199872',
    rating: 4,
    stock: 12,
  },

  // OTHER
  {
    name: 'Cat Keychain Set',
    category: 'OTHER',
    description: 'A set of metal keychains featuring different cat designs.',
    price: 10,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/16.jpg?updatedAt=1739952826217',
    rating: 5,
    stock: 40,
  },
  {
    name: 'Reusable Cat Tote Bag',
    category: 'OTHER',
    description: 'An eco-friendly tote bag with a minimalist cat print.',
    price: 15,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/OTHER.jpg?updatedAt=1739289199898',
    rating: 4,
    stock: 18,
  },
  {
    name: 'Cat-Themed Phone Case',
    category: 'OTHER',
    description: 'A durable phone case featuring an artistic cat illustration.',
    price: 20,
    image: 'https://ik.imagekit.io/h4sspbp2a/products/27.jpg?updatedAt=1739954048533',
    rating: 4,
    stock: 25,
  },
];
